project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mt-digital
      - icon: twitter
        href: https://twitter.com/MATurnerPhD
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

